### ISSUE TITLE
【bug】生成报告时报错

### ISSUE THREAD

**Issue by zhaolixiao** [zhaolixiao/hello-world#16]
Traceback (most recent call last):
  File "devices.py", line 200, in <module>
    start_test(args)
  File "devices.py", line 187, in start_test
    write_to_excel(stftest, report_file)
  File "/starnet/zlx/hello-world/comptest/excel_report.py", line 429, in write_to_excel
    excel.add_summary('测试概述', devices)
  File "/starnet/zlx/hello-world/comptest/excel_report.py", line 225, in add_summary
    r_index = self.write_perform_summary(sheet, device_info_list, r_index)
  File "/starnet/zlx/hello-world/comptest/excel_report.py", line 265, in write_perform_summary
    get_avg_net_of_all(device_info_list)
  File "/starnet/zlx/hello-world/comptest/libs/report_parser.py", line 223, in get_avg_net_of_all
    return get_avg_of_sortlist(get_net_sortlist(devices))
  File "/starnet/zlx/hello-world/comptest/libs/report_parser.py", line 168, in get_net_sortlist
    value = max(float(res), float(req))
ValueError: could not convert string to float: None

**Comment by zhaolixiao** [comment]
异常处理，流量值判断不是数值时，直接跳过
if res != NON and req != NON:
            try:
                value = max(float(res), float(req))
            except ValueError, e:
                print '流量值不是数值', res, req
                continue
        elif res != NON:
            try:
                value = float(res)
            except ValueError, e:
                print '流量值不是数值', res
                continue
        elif req != NON:
            try:
                value = float(req)
            except ValueError, e:
                print '流量值不是数值', req
                continue
